"""initial_schema

Revision ID: 58f0e98a6c5f
Revises: 
Create Date: 2026-04-26 16:21:21.830430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58f0e98a6c5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('total_referrals', sa.Integer(), nullable=True),
    sa.Column('successful_loans', sa.Integer(), nullable=True),
    sa.Column('total_commission_earned', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('commission_pct', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('min_score', sa.Integer(), nullable=True),
    sa.Column('min_vintage_months', sa.Integer(), nullable=True),
    sa.Column('min_monthly_turnover', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_loan_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('min_loan_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interest_rate_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('interest_rate_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('processing_fee_pct', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('api_endpoint', sa.String(length=255), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('owner_phone', sa.String(length=15), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('vintage_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=True),
    sa.Column('ca_partner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ca_partner_id'], ['ca_partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin'),
    sa.UniqueConstraint('pan')
    )
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('aa_consent_id', sa.String(length=255), nullable=True),
    sa.Column('aa_consent_handle', sa.String(length=255), nullable=True),
    sa.Column('consent_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('data_date_from', sa.Date(), nullable=False),
    sa.Column('data_date_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aa_consent_id')
    )
    op.create_table('gst_filings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('return_type', sa.String(length=20), nullable=True),
    sa.Column('tax_period', sa.String(length=7), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('filed_on_time', sa.Boolean(), nullable=True),
    sa.Column('taxable_turnover', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_tax_paid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('b2b_turnover', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('b2c_turnover', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('cash_flow_score', sa.Integer(), nullable=True),
    sa.Column('gst_compliance_score', sa.Integer(), nullable=True),
    sa.Column('payment_discipline_score', sa.Integer(), nullable=True),
    sa.Column('business_vintage_score', sa.Integer(), nullable=True),
    sa.Column('revenue_growth_score', sa.Integer(), nullable=True),
    sa.Column('recommended_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('recommended_tenure_months', sa.Integer(), nullable=True),
    sa.Column('flags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('positive_factors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('improvement_areas', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('data_months', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('masked_account', sa.String(length=20), nullable=True),
    sa.Column('ifsc', sa.String(length=11), nullable=True),
    sa.Column('avg_monthly_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('avg_monthly_credits', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('avg_monthly_debits', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bounce_count_12m', sa.Integer(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('lender_id', sa.UUID(), nullable=False),
    sa.Column('risk_score_id', sa.UUID(), nullable=False),
    sa.Column('offered_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('processing_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('emi_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('offer_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('our_fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('our_fee_pct', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('txn_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('txn_type', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_transactions')
    op.drop_table('loan_offers')
    op.drop_table('bank_accounts')
    op.drop_table('risk_scores')
    op.drop_table('gst_filings')
    op.drop_table('consents')
    op.drop_table('businesses')
    op.drop_table('lenders')
    op.drop_table('ca_partners')
    # ### end Alembic commands ###
