"""add_audit_logs

Revision ID: 8ea67602f8ca
Revises: 5b12aaa7c755
Create Date: 2026-04-30 13:50:29.866422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea67602f8ca'
down_revision: Union[str, Sequence[str], None] = '5b12aaa7c755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Column add karo nullable=True (existing rows ke liye)
    op.add_column('lenders', sa.Column('api_key', sa.String(length=64), nullable=True))
    op.add_column('lenders', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('lenders', sa.Column('contact_name', sa.String(length=255), nullable=True))

    # Step 2: Existing rows mein temp value fill karo
    op.execute("UPDATE lenders SET api_key = 'cb_legacy_' || id::text WHERE api_key IS NULL")
    op.execute("UPDATE lenders SET contact_email = 'legacy@creditbridge.in' WHERE contact_email IS NULL")
    op.execute("UPDATE lenders SET contact_name = 'Legacy Lender' WHERE contact_name IS NULL")

    # Step 3: Ab NOT NULL enforce karo — safe hai kyunki sab rows filled hain
    op.alter_column('lenders', 'api_key', nullable=False)

    # Step 4: Unique constraint add karo
    op.create_unique_constraint('uq_lenders_api_key', 'lenders', ['api_key'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lenders_api_key', 'lenders', type_='unique')
    op.drop_column('lenders', 'api_key')
    op.drop_column('lenders', 'contact_email')
    op.drop_column('lenders', 'contact_name')
    # ### end Alembic commands ###
