"""consent_nullable

Revision ID: 90be1b37cdb0
Revises: 8ea67602f8ca
Create Date: 2026-05-01 13:39:08.383809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90be1b37cdb0'
down_revision: Union[str, Sequence[str], None] = '8ea67602f8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'consent_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'consent_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
